#!/usr/bin/env ruby

images = Dir['img/*.gif'].map{|i| {
  :path => i,
  :prob => i.split('/')[1].to_i}}

images.each do |img|
  prob_path = Dir["#{img[:prob].to_s.rjust(3, '0')}-*.md"][0]

  if prob_path
    prob = File.open(prob_path, 'r').read
    prob = prob.split("\n").insert(1, "").insert(2, "![p#{img[:prob].to_s.rjust(3, '3')}](#{img[:path]})").insert(3, "").join("\n")
    File.open(prob_path, 'w').write(prob)
  else
    puts "prob path not found for problem #{img[:prob]}"
  end
end


