#!/usr/bin/env ruby

puts "// file: all.c"
puts "// autogenerated from *_test.c in test/ by all.rb"
puts "// don't modify this file - it will be overwritten"
puts "// this script assumes it's begin ran from within the test/ directory"

inputfiles = Dir["???.c"]
tests = []

puts "#define EULER_TEST_MAIN"
puts "#include <euler/test.h>"
puts

inputfiles.each do |inputfile|
  input = File.read(inputfile)
  input.scan(/void\s+(\w+)/).each do |match|
    tests << match[0]
  end
end

tests.each do |test|
  puts "void #{test}();"
end

puts

puts "TESTS() {"
tests.each do |test|
  puts "  RUN(#{test});"
end
puts "}"
